global:
  scrape_interval: 5s  # How often to scrape targets
  evaluation_interval: 5s  # How often to evaluate rules

scrape_configs:
  # Producer metrics
  - job_name: 'binance-producer'
    static_configs:
      - targets: ['binance-producer:8000']

  # Prices Consumer metrics
  - job_name: 'prices-consumer'
    static_configs:
      - targets: ['prices-consumer:8001']

  # Spark Processor metrics
  - job_name: 'spark-processor'
    static_configs:
      - targets: ['spark-processor:8002']

  # Alerts Consumer metrics
  - job_name: 'alerts-consumer'
    static_configs:
      - targets: ['alerts-consumer:8003']

  # Kafka metrics (consumer lag, etc.)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Container metrics (CPU, memory, etc.)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Clock Skew Monitor metrics
  - job_name: 'clock-skew-monitor'
    static_configs:
      - targets: ['clock-skew-monitor:8004']